### ISSUE TITLE
Confusion about data files

### ISSUE THREAD

**Issue by Feng-Jay** [ZZR0/ISSTA21-JIT-DP#2]
Hi, your paper has done a great job and upload a wonderful dataset! 
But I was a liitle confused after downloading the data files you uploaded on [google drive](https://drive.google.com/file/d/1XvrxRjWAYo3qQY4x75nbT4PoYqlTISLJ/view).

For example:
In your paper's table I, it illustrates the number of changes on JDT is 13348. But when I search the files in `data/jdt/`. I hardly find a .pkl file or .csv file that fit this number.

Am i missing some files?Can you help me with that? 

Finally, thanks to your great work.

**Comment by ZZR0** [comment]
Hello Feng-Jay. In our paper, Table 1 displays the complete collection of changes data, encompassing all changes throughout a 10-year period. When performing various experiments, we utilize distinct portions of the dataset. Consequently, each file you observe constitutes a part of the entire dataset, and the aggregate of their changes should approximate the data presented in Table 1.

It is crucial to recognize that different algorithms might subject the changes data to additional filtering and processing. The data available in Google Drive has undergone such secondary filtering, which may result in discrepancies between these data and those in Table 1. If you are interested in obtaining a comprehensive, unprocessed dataset, we encourage you to follow the provided tutorial (i.e., Complete Evaluation Section) to recollect the entire changes data.
