### ISSUE TITLE
关于收集数据集

### ISSUE THREAD

**Issue by TaoZheng-code** [ZZR0/ISSTA21-JIT-DP#3]
作者你好，感谢你提供的代码。我想知道如何将项目替换成其他项目，要如何收集其他项目的数据集，来跑这些模型。Data_Extraction中的代码也是关于这几个项目的数据收集，而且repo_urls.txt中的链接好像失效了。

**Comment by ZZR0** [comment]
如果要拓展其他的新项目您可能需要参照Data_Extraction中原有项目的代码，提供新项目的一些信息，比如其Git链接，对应的issue report信息等。然后参照Complete Evaluation中的流程重新收集数据。

**Comment by TaoZheng-code** [comment]
感谢作者百忙之中解答，我尝试一下您的方法。
